source/api_v1/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from api_v1 import views

router = routers.DefaultRouter()
router.register(r'comments', views.CommentViewSet)
router.register(r'likes', views.LikeViewSet)

app_name='api_v1'

urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token, name='api_token_auth'),
    path('logout/', views.LogoutView.as_view(), name='logout_user'),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from main import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('api/v1/', include('api_v1.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import IndexView, PhotoDetailedView, PhotoCreateView, PhotoUpdateView, UserLoginView, UserLogoutView

urlpatterns = [
    path('', IndexView.as_view(), name='main_page'),
    path('photos/<int:pk>/', PhotoDetailedView.as_view(), name='photo_detailed'),
    path('photos/<int:pk>/', PhotoUpdateView.as_view(), name='photo_edit'),
    path('photos/add/', PhotoCreateView.as_view(), name='photo_add'),

    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout')
]

app_name='webapp'

source/api_v1/models.py
from django.db import models

# Create your models here.

source/webapp/models.py
from django.contrib.auth.models import User
from django.db import models

class Photo(models.Model):
    photo = models.ImageField(null=False, blank=False, upload_to='photos', verbose_name='Фотография')
    description = models.CharField(max_length=150, null=False, blank=False, verbose_name='Подпись')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')
    likes = models.IntegerField(default=0, verbose_name='Лайки')
    author = models.ForeignKey(User, null=False, on_delete=models.CASCADE, blank=False,verbose_name='Автор')

    def __str__(self):
        return "Фото {} пользователя {}".format(self.description[:10], self.author.username)

class Comment(models.Model):
    text = models.TextField(max_length=300, null=False, blank=False, verbose_name='Комментарий')
    photo = models.ForeignKey('webapp.Photo', null=False, related_name='comments', on_delete=models.CASCADE, blank=False, verbose_name='Фотография')
    author = models.ForeignKey(User, null=False,blank=False, related_name='comments', on_delete=models.CASCADE, verbose_name='Автор комментария')
    added = models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')

    def __str__(self):
        return "Комментарий пользователя {} о фотографии {}".format(self.author.username, self.photo.description[:10])

class Like(models.Model):
    user = models.ForeignKey(User, related_name='likes_added', on_delete=models.CASCADE, verbose_name='Автор лайка')
    photo = models.ForeignKey('webapp.Photo', related_name='likes_received', null=False, blank=False, on_delete=models.CASCADE, verbose_name='Понравившаяся фотография')

source/api_v1/views.py
import django_filters
from django.http import Http404
from rest_framework.permissions import IsAuthenticated, DjangoModelPermissions
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import viewsets, status

from api_v1.permissions import CommentAuthorOrReadOnly, LikeAuthenticatedAddOnly
from api_v1.serializers import UserSerializer, CommentSerializer, LikeSerializer
from webapp.models import Comment, Photo, Like


class CommentViewSet(viewsets.ModelViewSet):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = [CommentAuthorOrReadOnly | DjangoModelPermissions]

class LikeViewSet(viewsets.ModelViewSet):
    queryset = Like.objects.all()
    serializer_class = LikeSerializer
    # filterset_fields = ['photo']

    def create(self, request, *args, **kwargs):
        pk = request.data.get('photo')
        photo = Photo.objects.get(pk=pk)
        if self.queryset.filter(photo=photo):
            return Response({'error': 'you cannot like the same photo twice' }, status=400)
        photo.likes += 1
        photo.save()
        return super(LikeViewSet, self).create(request, *args, **kwargs)

    def destroy(self, request, *args, **kwargs):
        instance = self.get_object()
        self.perform_destroy(instance)
        photo = Photo.objects.get(pk=instance.photo.pk)
        photo.likes -= 1
        photo.save()
        return Response(status=status.HTTP_204_NO_CONTENT)

class RegisterView(APIView):
    permission_classes = []

    def post(self, request, *args, **kwargs):
        serializer  = UserSerializer(data=request.data)
        if serializer.is_valid():
            user = serializer.save()
            return Response({'response': 'Регистрация прошла успешно!',
                             'first_name': user.first_name,
                             'last_name': user.last_name})
        else:
            return Response({serializer.errors})



class LogoutView(APIView):
    permission_classes = []

    def post(self, request, *args, **kwargs):
        user = request.user
        if user.is_authenticated:
            user.auth_token.delete()
        return Response({'status': 'ok', 'message':'Вы вышли'})

source/webapp/views/photos.py
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.models import Photo


class IndexView(ListView):
    template_name = 'index.html'
    model = Photo
    ordering = ['-created_at']
    context_object_name = 'photos'


class PhotoDetailedView(DetailView):
    model = Photo
    template_name = 'photo/photo_detailed.html'


class PhotoCreateView(CreateView):
    model = Photo
    template_name = 'photo/photo_create.html'
    fields = ['photo', 'description']

    def get_success_url(self):
        return reverse('webapp:photo_detailed', kwargs = {'pk': self.object.pk})

    def form_valid(self, form):
        self.object = Photo.objects.create(author = self.request.user, photo = form.cleaned_data['photo'],
                                           description=form.cleaned_data['description'])
        return HttpResponseRedirect(self.get_success_url())

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('webapp:login')
        return super(PhotoCreateView, self).dispatch(request, *args, **kwargs)

class PhotoUpdateView(UpdateView):
    model = Photo
    fields = ['photo', 'description']
    template_name = 'photo/photo_update.html'

    def get_success_url(self):
        return reverse('webapp:photo_detailed', kwargs={'pk': self.object.pk})

    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perm('webapp.change_photo') or self.object.author != request.user:
            raise PermissionDenied('403 Forbidden')
        return super(PhotoUpdateView, self).dispatch(request, *args, **kwargs)

class PhotoDeleteView(DeleteView):
    model = Photo
    template_name = 'photo/photo_delete.html'

    def get_success_url(self):
        return reverse('webapp:main_page')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perm('webapp.delete_photo') or self.object.author != request.user:
            raise PermissionDenied('403 Forbidden')
        return super(PhotoDeleteView, self).dispatch(request, *args, **kwargs)

source/webapp/views/user.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LogoutView, LoginView
from django.shortcuts import redirect, render


class UserLoginView(LoginView):
    template_name = 'login.html'
    success_url = 'webapp:main_page'

# def login_view(request):
#     context={}
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         redirect_path = request.GET.get('next')
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request, user)
#             if redirect_path:
#                 return redirect(redirect_path)
#             return redirect('webapp:main_page')
#         else:
#             context['has_error']=True
#             context['next']=redirect_path
#             context['username']=username
#
#     else:
#         context={'next': request.GET.get('next')}
#     return render(request, 'login.html', context=context)


class UserLogoutView(LogoutView):
    next_page = 'webapp:main_page'

source/webapp/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "/css/style.css" %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    {% block style_links %}{% endblock %}
</head>
<body>
<div class="container mt-3">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'webapp:main_page' %}">Главная<span class="sr-only">(current)</span></a>
                </li>
                {% block menu_links %}{% endblock %}
                {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'webapp:login' %}" class="nav-link">Войти в трекер</a>
                    </li>
                {% else %}
                    <span class="ml-3 navbar-text">Вы вошли как {{ request.user.username }}</span>
                    <a href="{% url 'webapp:photo_add' %}" class="nav-link">Добавить фото</a>
                    <a href="{% url 'webapp:logout' %}" class="nav-link">Выйти из трекера</a>
                {% endif %}

            </ul>
        </div>
    </nav>

    {% block content %}{% endblock %}
</div>
<script src={% static "/js/jquery-3.4.1.min.js"%}></script>
<script src={% static "/js/popper.min.js"%}></script>
<script src={% static "/js/bootstrap.min.js"%}></script>
<script src="{% static '/js/api.js' %}"></script>
{% block script %}{% endblock %}
</body>
</html>

source/webapp/templates/index.html
{% extends 'base.html' %}
{% block title %}
    Главная
{% endblock %}
{% block content %}

    <div class="row pt-5">
        {% for photo in photos %}
            <div class="col-sm-4">
                <div class="card">
                    <img src="{{ photo.photo.url }}" class="card-img-top ml-auto mr-auto" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ photo.description }}</h5>
                        <p class="card-text">Добавлено: {{ photo.author }}, {{ photo.created_at }}</p>
                        <p class="card-text">Лайков: {{ photo.likes }}</p>
                        <a href="{% url 'webapp:photo_detailed' photo.pk %}" class="btn btn-primary">Детальный просмотр</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

source/webapp/templates/login.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Вход</h1>
    <div class="d-flex row justify-content-center">
        <div class="pt-5 w-25">
            <form action="" method="post" class="text-center">
                {% csrf_token %}
                {% if has_error %}
                    <p class="form-error">Неверное имя пользователя или пароль.</p>
                {% endif %}
                <div class="form-group">
                    <label for="username" class="form-label">Имя пользователя:</label>
                    <input type="text" name="username" id="username" class="form-control">
                </div>

                <div class="form-group">
                    <label for="password" class="form-label">Пароль:</label>
                    <input type="password" name="password" id="password" class="form-control">
                </div>

                <div class="form-group d-inline position-relative">
                    <input class="form-control position-relative"
                                   type="hidden" name= "redirect_url" value={{ redirect_url }}>
                </div>

                <button type="submit" class="btn btn-success">Войти</button>

            </form>
        </div>
    </div>

{% endblock %}

source/webapp/templates/partial/form.html
{% load widget_tweaks %}
{% csrf_token %}
{% for error in form.non_field_errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}
{% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}" class="mr-3">{{ field.label }}</label>
        {% if field|field_type == 'imagefield' or field|field_type == 'filefield' %}
            {{ field }}
        {% else %}
            {{ field|add_class:"form-control" }}
        {% endif %}
        {% for error in field.errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}
    </div>
{% endfor %}

source/webapp/templates/photo/photo_create.html
{% extends 'base.html' %}
{% block title %}Добавить фото{% endblock %}
{% block content %}
    <h1 class="text-center">Добавить фотографию</h1>
    <form action="{% url "webapp:photo_add" %}" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' %}
        <input type="submit" value="Создать" class="btn btn-primary">
    </form>
{% endblock %}

source/webapp/templates/photo/photo_delete.html
{% extends 'base.html' %}

{% block title %}Удаление фото{% endblock %}
{% block content %}
    <div class = "d-flex flex-column justify-content-center pt-5 pb-5">
        <h1>Удаление фотографии</h1>
        <h2><strong>Описание фотографии:</strong> {{ photo.description }}</h2>
        <h5>Вы уверены, что хотите удалить выбранную задачу?</h5>
        <form method="POST" action="{% url 'webapp:delete task' photo.pk %}">
            {% csrf_token %}
            <div class = "btn-group pl-5">
                <input type="submit" class  = 'btn btn-outline-warning' value="Confirm">
                <a type="submit" class  = 'btn btn-outline-warning' href="{% url 'webapp:photo_detailed' photo.pk %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

source/webapp/templates/photo/photo_detailed.html
{% extends 'base.html' %}
{% block title %}
    Просмотр
{% endblock %}
{% block menu_links %}
    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a href="{% url 'webapp:photo_edit' photo.pk %}" class="nav-link">Редактировать фото</a>
        </li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="card text-center">
        <img src="{{ photo.photo.url }}" style="width:50%" class="card-img-top ml-auto mr-auto" alt="..." id="photo" data-info="{{ photo.pk }}">
        <div class="row justify-content-center">
            <div class="btn-group">

                <button class="btn btn-outline-danger" id ="addLike"><i class="fas fa-heart"></i></button>
                {% if photo.likes_received %}
                <input type="hidden" id="likeAdded" value="{{ photo.likes_received.first.id }}">
                {% else %}
                     <input type="hidden" id="likeAdded">
                {% endif %}
                <button class="btn btn-danger" id="removeLike"><i class="fas fa-thumbs-down"></i></button>
                <span id="likesTotal" class="btn btn-danger disabled">{{ photo.likes }}</span>
            </div>

        </div>
        <div class="card-body">
            <h5 class="card-title">Добавлено: {{ photo.author }},  {{ photo.created_at }}</h5>
            <p class="card-text"><strong>Описание: </strong>{{ photo.description }}</p>
        </div>
        <button type="button" class="btn btn-primary w-50 ml-auto mr-auto" data-toggle="modal" data-target="#commentModal">
            Добавить комментарий
        </button>
        <div class="ml-auto mr-auto card-footer w-50">
            <div class="list-group" id="commentsList">
                {% for comment in photo.comments.all %}
                    <div class="list-group-item">
                        <div class="d-flex w-100 justify-content-between">

                            <h5 class="mb-1">{{ comment.author }}</h5>
                            <small>{{ comment.added }}</small>

                        </div>
                        <p class="mb-1 text-left">{{ comment.text }}</p>
                        <button class="delete btn btn-danger" id={{ comment.id }}><i class="fas fa-trash-alt"></i></button>
                    </div>

                {% endfor %}
            </div>
        </div>
    </div>


    <div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Добавить комментарий</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        {% csrf_token %}
                        <label for="commentText">Комментарий</label>
                        <input type="hidden" value="{{ photo.pk }}" id="commentPhoto">
                        <input type="hidden" value="{{ request.user.id }}" id="commentAuthor">
                        <textarea class="form-control" id="commentText" rows="3"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="commentAdd">Добавить комментарий</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

source/webapp/templates/photo/photo_update.html
{% extends 'base.html' %}
{% block title %}Обновить фото{% endblock %}
{% block content %}
    <h1 class="text-center">Обновить фото</h1>
    <form action="{% url "webapp:photo_edit"  photo.pk %}" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' %}
        <input type="submit" value="Создать" class="btn btn-primary">
    </form>
{% endblock %}